name: CI for ml-service 
on: 
    push:
      paths: 
       - 'ml-service/**'
    pull_request:
      paths: 
        - 'ml-service/**'
    workflow_dispatch:
jobs:
  ML_Service_CI: 
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Set Up Python 
        uses: actions/setup-python@v5
        with:
         python-version: '3.11'
      - name: Install Uv
        run: pip install uv
      - name: Install dependancies using uv
        working-directory: ml-service
        run: uv pip install --system -r requirements.txt 
      - name: Run Pytest
        working-directory: ml-service
        run: echo "This is a placeholder for pytest tests/"
      - name: Set Docker build x
        uses: docker/setup-buildx-action@v3
        
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
           context: ./ml-service
           push: false
           tags: jasper-ml-service:${{ github.sha }}
       