name: CI for ml-service 
on: 
    push:
      paths: 
       - 'ml-service/**'
    pull_request:
      paths: 
        - 'ml-service/**'
    workflow_dispatch:
env: 
  REGION: us-central1
  REGISTRY: us-central1-docker.pkg.dev
  IMAGE_NAME: jasper-ml-service
jobs:
  ML_Service_CI: 
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Set Up Python 
        uses: actions/setup-python@v5
        with:
         python-version: '3.11'
      - name: Install Uv
        run: pip install uv
      - name: Install dependancies using uv
        working-directory: ml-service
        run: uv pip install --system -r requirements.txt 
      - name: Run Pytest
        working-directory: ml-service
        run: echo "This is a placeholder for pytest tests/"
      
      - name: Authenticate cloud sdk
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup google cloud
        uses: google-github-actions/setup-gcloud@v2


      - name: Configure Docker for GAR
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Set Docker build x
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
            context: ./ml-service
            push: true
            tags: |
              ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/jasper-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}
              ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/jasper-repo/${{ env.IMAGE_NAME }}:latest